language: cpp
sudo: false
cache:
  directories:
  - depends/built
before_script:
    - unset CC; unset CXX
    - make $MAKEOPTS -C depends HOST=$HOST
    - make -C depends HOST=$HOST install
script:
    - ./autogen.sh
    - ./configure --prefix=`pwd`/depends/$HOST $GLOBALOPTS $OPTS
    - make $MAKEOPTS
os: linux
env:
  global:
    - MAKEOPTS=-j2
    - GLOBALOPTS=--disable-dependency-tracking
  matrix:
    - HOST=x86_64-unknown-linux-gnu

